version: '3'

services:
    hugo:
        image: jakejarvis/hugo-extended:latest
        ports:
            - 1313:1313
        volumes:
            - ./:/src
        command: server --buildDrafts --buildFuture --bind 0.0.0.0
